# Generated by Django 5.2.4 on 2025-07-27 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدورة')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='الطلاب المشتركين')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-created_at'],
            },
        ),
    ]
