# Generated by Django 5.2.4 on 2025-07-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_comment_content_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='نشر الدورة'),
        ),
    ]
