# Generated by Django 5.2.4 on 2025-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدة الدورة'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مستوى الدورة'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, null=True, verbose_name='متطلبات الدورة'),
        ),
    ]
